name: Internet_access by Tailscale

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup-tailscale:
    runs-on: ubuntu-latest
    timeout-minutes: 50  # 设置工作流超时为45分钟

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    
        

    - name: 预设置Tailscale
      run: |
        sudo -s  # 切换到 root 用户
        curl -fsSL https://tailscale.com/install.sh | sh
        echo 'net.ipv4.ip_forward = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf
        echo 'net.ipv6.conf.all.forwarding = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf
        sudo sysctl -p /etc/sysctl.d/99-tailscale.conf
    - name: 登入Tailscale
      env:
        TSAUTHKEY: ${{ secrets.ts_authkey }}
      run: |
        
        # 启动 Tailscale
        sudo tailscale up --auth-key=$TSAUTHKEY
    - name: 声明出口节点
      run: |
        
        # 使用 advertise-exit-node 选项启动 Tailscale
        sudo tailscale up --advertise-exit-node
    - name: Ensure workflow runs for 45 minutes
      run: sleep $((45*60))  # 睡眠45分钟，确保工作流运行到45分钟
