name: Tailscale Setup

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup-tailscale:
    runs-on: ubuntu-latest
    timeout-minutes: 45  # 设置工作流超时为45分钟

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Tailscale setup
      run: |
        sudo -s  # 切换到root用户
        curl -fsSL https://tailscale.com/install.sh | sh
        echo 'net.ipv4.ip_forward = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf
        echo 'net.ipv6.conf.all.forwarding = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf
        sudo sysctl -p /etc/sysctl.d/99-tailscale.conf

    - name: Run tailscale up
      run: sudo tailscale up --authkey=${{ ts_authkey }}

    - name: Run tailscale up with advertise-exit-node
      run: sudo tailscale up --authkey=${{ ts_authkey }} --advertise-exit-node

    - name: Ensure workflow runs for 45 minutes
      run: sleep $((45*60))  # 睡眠45分钟，确保工作流运行到45分钟
